Repository scil-vital/dwi_ml, pull requests merged in 2020-04, with the labels that each got.

#32 ENH: Pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#33 BUG: Add missing `sphinx_rtd_theme` package to doc requirements
  doc/requirements_doc.txt
Labels: bug, documentation

#34 ENH: Add commit message-related pre-commit hooks
  utils/gitsetup/setup-hooks.sh
  utils/hooks/commit-msg
  utils/hooks/prepare-commit-msg
Labels: documentation, enhancement
